---
services:
  ts-n8n:
    image: tailscale/tailscale:latest
    container_name: n8n-tailscale
    hostname: ${TAILSCALE_HOSTNAME}
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container --reset
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    ports:
      - "${PUBLIC_PORT:-5678}:5678"

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n-app
    network_mode: service:ts-n8n
    depends_on:
      - ts-n8n
    user: "1000:1000"               # keep data files owned by your host user (adjust as needed)
    volumes:
      - n8n-data:/home/node/.n8n     # n8n persistent data (workflows, creds metadata, etc.)
    environment:
      # Core n8n config
      - NODE_ENV=production
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_HOST=${N8N_HOST}
      - WEBHOOK_URL=${N8N_WEBHOOK_URL:-}
      - GENERIC_TIMEZONE=${N8N_TZ:-America/Toronto}

      # Security / privacy
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-}     # strongly recommended: set a 32+ char random string
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE:-false}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-false}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-}
      - N8N_DIAGNOSTICS_ENABLED=${N8N_DIAGNOSTICS_ENABLED:-false}
      - N8N_PERSONALIZATION_ENABLED=${N8N_PERSONALIZATION_ENABLED:-false}

      # Executions
      - EXECUTIONS_PROCESS=${N8N_EXECUTIONS_PROCESS:-main}  # 'main' or 'queue' (requires Redis if 'queue')
      - N8N_METADATA_EXPOSED_HEADERS=${N8N_METADATA_EXPOSED_HEADERS:-}

      # Misc
      - TZ=${N8N_TZ:-America/Toronto}
    restart: unless-stopped

volumes:
  n8n-data:
    driver: local
